### ISSUE TITLE
Как с Вами связаться?

### ISSUE THREAD

**Issue by DeadSca** [2020karaulov2020/UnrealDemoScanner#9]
Интересует разработка подобного софта под CS:GO. Готовы обсудить варианты сотрудничества
если интересует то свяжитесь пожалуйста 1м из способов связи(или тут ответьте - я буду мониторить)
мой ТГ: https://t.me/DeadScorpi0n
или ВК рабочий: https://vk.com/gamereason

**Comment by 2020karaulov2020** [comment]
@DeadSca не обнаружил парсера
